version: "3.8"

services:
  arcadia_db:
    image: postgres
    ports:
      - "5432:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_SCHEMA}
    volumes:
      - pgdata:/var/lib/postgres/data
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
  backend: 
    image: arcadia-backend-dev:latest
    container_name: backend_arcadia_dev
    depends_on:
      - arcadia_db
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "3001:${BACKEND_PORT}"
    volumes:
      - ./backend:/backend

  # frontend:
  #   image: arcadia_frontend
  #   container_name: arcadia_frontend
  #   depends_on:
  #     - arcadia_db
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:${FRONTEND_PORT}"
volumes:
  pgdata:

